language: python
python:
    - "3.6"
    - "3.5"
    - "3.4"
    - "2.7"
env:
    - DJANGO_VERSION=1.9.13
    - DJANGO_VERSION=1.10.7
    - DJANGO_VERSION=1.11
matrix:
  exclude:
    - python: "3.6"
      env: DJANGO_VERSION=1.9.13
    - python: "3.6"
      env: DJANGO_VERSION=1.10.7
before_install:
    - export DJANGO_SETTINGS_MODULE="regwall.tests.settings"
install:
    - pip install -q Django==$DJANGO_VERSION
    - python setup.py -q install
    - django-admin migrate
    - django-admin loaddata articles_article.json
script:
    - django-admin test regwall.tests